// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using QuanLyLinhKienMayTinh.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial interface IQL_LinhKien_PC_ContextProcedures
    {
        Task<int> sp_BanLinhKienAsync(DateOnly? ngayHD, string maKH, string maNV, string maLK, byte? soLuongBan, OutputParameter<string> maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_BaoCaoTonKhoResult>> sp_BaoCaoTonKhoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_DanhSacKhachHangChuaTTResult>> sp_DanhSacKhachHangChuaTTAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_ThanhToanHoaDonAsync(string maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_XoaHoaDonAsync(string maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
