// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using QuanLyLinhKienMayTinh.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial interface IQL_LinhKien_PC_ContextProcedures
    {
        Task<int> sp_BanLinhKienAsync(DateOnly? ngayHD, string maKH, string maNV, string maLK, byte? soLuongBan, OutputParameter<string> maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_baocaotonkhoResult>> sp_baocaotonkhoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_DanhSacKhachHangChuaTTResult>> sp_DanhSacKhachHangChuaTTAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_kichban1_giaotacaAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_kichban1_giaotacbAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_kichban2_giaotacaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_kichban2_giaotacbResult>> sp_kichban2_giaotacbAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_kichban3_giaotacaResult>> sp_kichban3_giaotacaAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_kichban3_giaotacbAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_kichban4_giaotacaResult>> sp_kichban4_giaotacaAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_kichban4_giaotacbAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_kichban5_giaotacaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_kichban5_giaotacbAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_kichban6_giaotac_rollbackResult>> sp_kichban6_giaotac_rollbackAsync(string maLK, int? soLuongBan, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_locdanhsachhoadonResult>> sp_locdanhsachhoadonAsync(string tukhoan, string trangthai, DateOnly? tungay, DateOnly? denngay, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_locdanhsachphieunhapResult>> sp_locdanhsachphieunhapAsync(string tukhoan, DateOnly? tungay, DateOnly? denngay, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_NhapLinhKienAsync(DateOnly? ngayNhap, string maNV, string maNSX, string maLK, int? soLuongNhap, int? donGiaNhap, OutputParameter<string> maPN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_TaiChiTietPNResult>> sp_TaiChiTietPNAsync(string maPN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_TaiChiTietSPResult>> sp_TaiChiTietSPAsync(string maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_ThanhToanHoaDonAsync(string maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_ThongKeAsync(OutputParameter<int?> tongHoaDon, OutputParameter<decimal?> tongDoanhThu, OutputParameter<int?> daThanhToan, OutputParameter<int?> chuaThanhToan, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_ThongKePhieuNhapAsync(OutputParameter<int?> tongPhieuNhap, OutputParameter<decimal?> tongChiPhiNhap, OutputParameter<int?> tongSoLuongNhap, OutputParameter<int?> soPhieuNhapThangNay, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_XoaHoaDonAsync(string maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_XoaPhieuNhapAsync(string maPN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
