// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using QuanLyLinhKienMayTinh.Models;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class QL_LinhKien_PC_Context
    {

        [DbFunction("fn_DoanhThuTheoThang", "dbo")]
        public static int? fn_DoanhThuTheoThang(int? Thang, int? Nam)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("fn_TaoMaHoaDonMoi", "dbo")]
        public static string fn_TaoMaHoaDonMoi()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<string> fn_TaoMaHoaDonMoiAsync()
            => await Database.SqlQueryRaw<string>("select Value = [dbo].[fn_TaoMaHoaDonMoi]()").SingleAsync();

        [DbFunction("fn_TaoMaKhachHangMoi", "dbo")]
        public static string fn_TaoMaKhachHangMoi()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<string> fn_TaoMaKhachHangMoiAsync()
            => await Database.SqlQueryRaw<string>("select Value = [dbo].[fn_TaoMaKhachHangMoi]()").SingleAsync();

        [DbFunction("fn_TaoMaLinhKienMoi", "dbo")]
        public static string fn_TaoMaLinhKienMoi(string MaLoai)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("fn_TaoMaNhanVienMoi", "dbo")]
        public static string fn_TaoMaNhanVienMoi()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        public async Task<string> fn_TaoMaNhanVienMoiAsync()
            => await Database.SqlQueryRaw<string>("select Value = [dbo].[fn_TaoMaNhanVienMoi]()").SingleAsync();

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
