// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using QuanLyLinhKienMayTinh.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class QL_LinhKien_PC_Context
    {
        private IQL_LinhKien_PC_ContextProcedures _procedures;

        public virtual IQL_LinhKien_PC_ContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new QL_LinhKien_PC_ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IQL_LinhKien_PC_ContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class QL_LinhKien_PC_ContextProcedures : IQL_LinhKien_PC_ContextProcedures
    {
        private readonly QL_LinhKien_PC_Context _context;

        public QL_LinhKien_PC_ContextProcedures(QL_LinhKien_PC_Context context)
        {
            _context = context;
        }

        public virtual async Task<int> sp_BanLinhKienAsync(DateOnly? ngayHD, string maKH, string maNV, string maLK, byte? soLuongBan, OutputParameter<string> maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterMaHD = new SqlParameter
            {
                ParameterName = "MaHD",
                Size = 5,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = maHD?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Char,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterMaHD,
                new SqlParameter
                {
                    ParameterName = "NgayHD",
                    Value = ngayHD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "MaKH",
                    Size = 6,
                    Value = maKH ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                new SqlParameter
                {
                    ParameterName = "MaNV",
                    Size = 6,
                    Value = maNV ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                new SqlParameter
                {
                    ParameterName = "MaLK",
                    Size = 6,
                    Value = maLK ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                new SqlParameter
                {
                    ParameterName = "SoLuongBan",
                    Value = soLuongBan ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_BanLinhKien] @MaHD = @MaHD OUTPUT, @NgayHD = @NgayHD, @MaKH = @MaKH, @MaNV = @MaNV, @MaLK = @MaLK, @SoLuongBan = @SoLuongBan", sqlParameters, cancellationToken);

            maHD?.SetValue(parameterMaHD.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_baocaotonkhoResult>> sp_baocaotonkhoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_baocaotonkhoResult>("EXEC @returnValue = [dbo].[sp_baocaotonkho]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_DanhSacKhachHangChuaTTResult>> sp_DanhSacKhachHangChuaTTAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_DanhSacKhachHangChuaTTResult>("EXEC @returnValue = [dbo].[sp_DanhSacKhachHangChuaTT]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_kichban1_giaotacaAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "isfixmode",
                    Value = isfixmode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_kichban1_giaotaca] @isfixmode = @isfixmode", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_kichban1_giaotacbAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "isfixmode",
                    Value = isfixmode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_kichban1_giaotacb] @isfixmode = @isfixmode", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_kichban2_giaotacaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_kichban2_giaotaca]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_kichban2_giaotacbResult>> sp_kichban2_giaotacbAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "isfixmode",
                    Value = isfixmode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_kichban2_giaotacbResult>("EXEC @returnValue = [dbo].[sp_kichban2_giaotacb] @isfixmode = @isfixmode", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_kichban3_giaotacaResult>> sp_kichban3_giaotacaAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "isfixmode",
                    Value = isfixmode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_kichban3_giaotacaResult>("EXEC @returnValue = [dbo].[sp_kichban3_giaotaca] @isfixmode = @isfixmode", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_kichban3_giaotacbAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_kichban3_giaotacb]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_kichban4_giaotacaResult>> sp_kichban4_giaotacaAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "isfixmode",
                    Value = isfixmode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_kichban4_giaotacaResult>("EXEC @returnValue = [dbo].[sp_kichban4_giaotaca] @isfixmode = @isfixmode", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_kichban4_giaotacbAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_kichban4_giaotacb]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_kichban5_giaotacaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_kichban5_giaotaca]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_kichban5_giaotacbAsync(bool? isfixmode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "isfixmode",
                    Value = isfixmode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_kichban5_giaotacb] @isfixmode = @isfixmode", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_kichban6_giaotaca_rollbackResult>> sp_kichban6_giaotaca_rollbackAsync(string maLK, int? soLuongBan, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MaLK",
                    Size = 6,
                    Value = maLK ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                new SqlParameter
                {
                    ParameterName = "SoLuongBan",
                    Value = soLuongBan ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_kichban6_giaotaca_rollbackResult>("EXEC @returnValue = [dbo].[sp_kichban6_giaotaca_rollback] @MaLK = @MaLK, @SoLuongBan = @SoLuongBan", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_kichban6_giaotacb_docsaorollbackResult>> sp_kichban6_giaotacb_docsaorollbackAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_kichban6_giaotacb_docsaorollbackResult>("EXEC @returnValue = [dbo].[sp_kichban6_giaotacb_docsaorollback]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_locdanhsachhoadonResult>> sp_locdanhsachhoadonAsync(string tukhoan, string trangthai, DateOnly? tungay, DateOnly? denngay, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "tukhoan",
                    Size = 200,
                    Value = tukhoan ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "trangthai",
                    Size = 60,
                    Value = trangthai ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "tungay",
                    Value = tungay ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "denngay",
                    Value = denngay ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_locdanhsachhoadonResult>("EXEC @returnValue = [dbo].[sp_locdanhsachhoadon] @tukhoan = @tukhoan, @trangthai = @trangthai, @tungay = @tungay, @denngay = @denngay", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_locdanhsachphieunhapResult>> sp_locdanhsachphieunhapAsync(string tukhoan, DateOnly? tungay, DateOnly? denngay, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "tukhoan",
                    Size = 200,
                    Value = tukhoan ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "tungay",
                    Value = tungay ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "denngay",
                    Value = denngay ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_locdanhsachphieunhapResult>("EXEC @returnValue = [dbo].[sp_locdanhsachphieunhap] @tukhoan = @tukhoan, @tungay = @tungay, @denngay = @denngay", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_NhapLinhKienAsync(DateOnly? ngayNhap, string maNV, string maNSX, string maLK, int? soLuongNhap, int? donGiaNhap, OutputParameter<string> maPN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterMaPN = new SqlParameter
            {
                ParameterName = "MaPN",
                Size = 5,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = maPN?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Char,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterMaPN,
                new SqlParameter
                {
                    ParameterName = "NgayNhap",
                    Value = ngayNhap ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "MaNV",
                    Size = 6,
                    Value = maNV ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                new SqlParameter
                {
                    ParameterName = "MaNSX",
                    Size = 5,
                    Value = maNSX ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                new SqlParameter
                {
                    ParameterName = "MaLK",
                    Size = 6,
                    Value = maLK ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                new SqlParameter
                {
                    ParameterName = "SoLuongNhap",
                    Value = soLuongNhap ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "DonGiaNhap",
                    Value = donGiaNhap ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_NhapLinhKien] @MaPN = @MaPN OUTPUT, @NgayNhap = @NgayNhap, @MaNV = @MaNV, @MaNSX = @MaNSX, @MaLK = @MaLK, @SoLuongNhap = @SoLuongNhap, @DonGiaNhap = @DonGiaNhap", sqlParameters, cancellationToken);

            maPN?.SetValue(parameterMaPN.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_TaiChiTietPNResult>> sp_TaiChiTietPNAsync(string maPN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MaPN",
                    Size = 5,
                    Value = maPN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_TaiChiTietPNResult>("EXEC @returnValue = [dbo].[sp_TaiChiTietPN] @MaPN = @MaPN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_TaiChiTietSPResult>> sp_TaiChiTietSPAsync(string maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MaHD",
                    Size = 5,
                    Value = maHD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Char,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_TaiChiTietSPResult>("EXEC @returnValue = [dbo].[sp_TaiChiTietSP] @MaHD = @MaHD", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_ThanhToanHoaDonAsync(string maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MaHD",
                    Size = 10,
                    Value = maHD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_ThanhToanHoaDon] @MaHD = @MaHD", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_ThongKeAsync(OutputParameter<int?> tongHoaDon, OutputParameter<decimal?> tongDoanhThu, OutputParameter<int?> daThanhToan, OutputParameter<int?> chuaThanhToan, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterTongHoaDon = new SqlParameter
            {
                ParameterName = "TongHoaDon",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = tongHoaDon?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterTongDoanhThu = new SqlParameter
            {
                ParameterName = "TongDoanhThu",
                Precision = 19,
                Scale = 4,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = tongDoanhThu?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Money,
            };
            var parameterDaThanhToan = new SqlParameter
            {
                ParameterName = "DaThanhToan",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = daThanhToan?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterChuaThanhToan = new SqlParameter
            {
                ParameterName = "ChuaThanhToan",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = chuaThanhToan?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterTongHoaDon,
                parameterTongDoanhThu,
                parameterDaThanhToan,
                parameterChuaThanhToan,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_ThongKe] @TongHoaDon = @TongHoaDon OUTPUT, @TongDoanhThu = @TongDoanhThu OUTPUT, @DaThanhToan = @DaThanhToan OUTPUT, @ChuaThanhToan = @ChuaThanhToan OUTPUT", sqlParameters, cancellationToken);

            tongHoaDon?.SetValue(parameterTongHoaDon.Value);
            tongDoanhThu?.SetValue(parameterTongDoanhThu.Value);
            daThanhToan?.SetValue(parameterDaThanhToan.Value);
            chuaThanhToan?.SetValue(parameterChuaThanhToan.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_ThongKePhieuNhapAsync(OutputParameter<int?> tongPhieuNhap, OutputParameter<decimal?> tongChiPhiNhap, OutputParameter<int?> tongSoLuongNhap, OutputParameter<int?> soPhieuNhapThangNay, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterTongPhieuNhap = new SqlParameter
            {
                ParameterName = "TongPhieuNhap",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = tongPhieuNhap?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterTongChiPhiNhap = new SqlParameter
            {
                ParameterName = "TongChiPhiNhap",
                Precision = 19,
                Scale = 4,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = tongChiPhiNhap?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Money,
            };
            var parameterTongSoLuongNhap = new SqlParameter
            {
                ParameterName = "TongSoLuongNhap",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = tongSoLuongNhap?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterSoPhieuNhapThangNay = new SqlParameter
            {
                ParameterName = "SoPhieuNhapThangNay",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = soPhieuNhapThangNay?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterTongPhieuNhap,
                parameterTongChiPhiNhap,
                parameterTongSoLuongNhap,
                parameterSoPhieuNhapThangNay,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_ThongKePhieuNhap] @TongPhieuNhap = @TongPhieuNhap OUTPUT, @TongChiPhiNhap = @TongChiPhiNhap OUTPUT, @TongSoLuongNhap = @TongSoLuongNhap OUTPUT, @SoPhieuNhapThangNay = @SoPhieuNhapThangNay OUTPUT", sqlParameters, cancellationToken);

            tongPhieuNhap?.SetValue(parameterTongPhieuNhap.Value);
            tongChiPhiNhap?.SetValue(parameterTongChiPhiNhap.Value);
            tongSoLuongNhap?.SetValue(parameterTongSoLuongNhap.Value);
            soPhieuNhapThangNay?.SetValue(parameterSoPhieuNhapThangNay.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_XoaHoaDonAsync(string maHD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MaHD",
                    Size = 10,
                    Value = maHD ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_XoaHoaDon] @MaHD = @MaHD", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_XoaPhieuNhapAsync(string maPN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MaPN",
                    Size = 10,
                    Value = maPN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_XoaPhieuNhap] @MaPN = @MaPN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
