// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class sp_baocaotonkhoResult
    {
        public string malk { get; set; }
        [StringLength(200)]
        public string tenlk { get; set; }
        [StringLength(100)]
        public string tenloai { get; set; }
        [StringLength(100)]
        public string tennsx { get; set; }
        public int? soluongton { get; set; }
    }
}
