// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class sp_DanhSacKhachHangChuaTTResult
    {
        public string MaHD { get; set; }
        [StringLength(30)]
        public string TenKH { get; set; }
        public string SDT { get; set; }
        public DateOnly? NgayLap { get; set; }
        [Column("SoTienNo", TypeName = "money")]
        public decimal? SoTienNo { get; set; }
    }
}
