// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class sp_kichban6_giaotaca_rollbackResult
    {
        [StringLength(65)]
        public string ThongBao { get; set; }
        [StringLength(6)]
        public string MaLK { get; set; }
        public int? SoLuongBan { get; set; }
        public int? TonKhoBanDau { get; set; }
        public int? TonKhoTamThoi { get; set; }
        public int? TonKhoKetThuc { get; set; }
        [StringLength(20)]
        public string TrangThai { get; set; }
    }
}
