// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class sp_kichban6_giaotacb_docsaorollbackResult
    {
        [StringLength(40)]
        public string ThongBao { get; set; }
        public int? TonKhoDocDuoc { get; set; }
    }
}
