// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class sp_locdanhsachphieunhapResult
    {
        public string mapn { get; set; }
        [StringLength(40)]
        public string tennv { get; set; }
        public DateOnly? ngaynhap { get; set; }
        [StringLength(50)]
        public string tennsx { get; set; }
        [StringLength(10)]
        public string sdtnsx { get; set; }
        public int tongsoluong { get; set; }
        [Column("tongtien", TypeName = "money")]
        public decimal? tongtien { get; set; }
    }
}
