// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class sp_locdanhsachhoadonResult
    {
        public string mahd { get; set; }
        [StringLength(30)]
        public string tenkh { get; set; }
        [StringLength(40)]
        public string tennv { get; set; }
        public DateOnly? ngayhd { get; set; }
        [Column("tongtien", TypeName = "money")]
        public decimal? tongtien { get; set; }
        [StringLength(50)]
        public string phuongthucthanhtoan { get; set; }
        [StringLength(30)]
        public string trangthai { get; set; }
    }
}
