// <auto-generated> This file matches the stored procedure result shape. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class sp_TaiChiTietPNResult
    {
        public string MaLinhKien { get; set; }
        [StringLength(50)]
        public string TenLinhKien { get; set; }
        public int? SoLuongNhap { get; set; }
        [Column("DonGiaNhap", TypeName = "money")]
        public decimal? DonGiaNhap { get; set; }
        [Column("ThanhTien", TypeName = "money")]
        public decimal? ThanhTien { get; set; }
    }
}
