// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class sp_TaiChiTietSPResult
    {
        [StringLength(50)]
        public string TenSanPham { get; set; }
        public byte? SoLuong { get; set; }
        [Column("DonGia", TypeName = "money")]
        public decimal? DonGia { get; set; }
        [StringLength(8)]
        public string HanBaoHanh { get; set; }
    }
}
