// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class TaiKhoan
{
    public string TenDn { get; set; }

    public string MatKhau { get; set; }

    public string MaNv { get; set; }

    public virtual NhanVien MaNvNavigation { get; set; }
}